#!/bin/bash

MYIP=$(wget -qO- ipv4.icanhazip.com);
echo "Checking VPS"
clear
source /var/lib/ipvps.conf
if [[ "$IP" = "" ]]; then
    domain=$(cat /etc/xray/domain)
else
    domain=$IP
fi

# Function to count the number of IPs connected to the user
count_ips() {
    user_ips=$(netstat -tn | grep ESTABLISHED | grep xray | grep ":$1" | awk '{print $5}' | cut -d: -f1 | sort | uniq)
    echo "$user_ips" | wc -l
}

while true; do
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "\\E[0;41;36m      Add Vmess Account      \E[0m"
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"

    read -rp "User name: " -e user
    CLIENT_EXISTS=$(grep -w "$user" /etc/xray/config.json | wc -l)

    if [[ $CLIENT_EXISTS -eq '1' ]]; then
        clear
        echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
        echo -e "\\E[0;41;36m      Add Vmess Account      \E[0m"
        echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
        echo ""
        echo "A client with the specified name was already created, please choose another name."
        echo ""
        echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
        read -n 1 -s -r -p "Press any key to back on menu"
        continue
    fi

    read -rp "Number of IPs (max 5): " -e num_ips
    if [[ $num_ips -lt 1 || $num_ips -gt 5 ]]; then
        echo "Number of IPs must be between 1 and 5."
        continue
    fi

    read -rp "Expiration months: " -e exp_months
    if [[ ! $exp_months =~ ^[0-9]+$ ]]; then
        echo "Invalid input. Please enter a valid number."
        continue
    fi

    uuid=$(cat /proc/sys/kernel/random/uuid)
    exp=$(date -d "+$exp_months months" +"%Y-%m-%d")
    sed -i '/#vmess$/a\### '"$user $exp"'\
    },{"id": "'"$uuid"'","alterId": '"0"',"email": "'"$user"'"' /etc/xray/config.json
    sed -i '/#vmessgrpc$/a\### '"$user $exp"'\
    },{"id": "'"$uuid"'","alterId": '"0"',"email": "'"$user"'"' /etc/xray/config.json
    asu=$(cat<<EOF
    {
    "v": "2",
    "ps": "${user}",
    "add": "${domain}",
    "port": "443",
    "id": "${uuid}",
    "aid": "0",
    "net": "ws",
    "path": "/vmess",
    "type": "none",
    "host": "",
    "tls": "tls"
}
EOF
)
    ask=$(cat<<EOF
    {
    "v": "2",
    "ps": "${user}",
    "add": "${domain}",
    "port": "80",
    "id": "${uuid}",
    "aid": "0",
    "net": "ws",
    "path": "/vmess",
    "type": "none",
    "host": "",
    "tls": "none"
}
EOF
)
    grpc=$(cat<<EOF
    {
    "v": "2",
    "ps": "${user}",
    "add": "${domain}",
    "port": "443",
    "id": "${uuid}",
    "aid": "0",
    "net": "grpc",
    "path": "vmess-grpc",
    "type": "none",
    "host": "",
    "tls": "tls"
}
EOF
)
    vmess_base641=$(base64 -w 0 <<< $vmess_json1)
    vmess_base642=$(base64 -w 0 <<< $vmess_json2)
    vmess_base643=$(base64 -w 0 <<< $vmess_json3)
vmesslink1="vmess://$(echo $asu | base64 -w 0)"
vmesslink2="vmess://$(echo $ask | base64 -w 0)"
vmesslink3="vmess://$(echo $grpc | base64 -w 0)"
systemctl restart xray > /dev/null 2>&1
service cron restart > /dev/null 2>&1
clear
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m" | tee -a /etc/log-create-vmess.log
echo -e "\E[0;41;36m Vmess Account \E[0m" | tee -a /etc/log-create-vmess.log
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m" | tee -a /etc/log-create-vmess.log
echo -e "Remarks : ${user}" | tee -a /etc/log-create-vmess.log
echo -e "Domain : ${domain}" | tee -a /etc/log-create-vmess.log
echo -e "Wildcard : (bug.com).${domain}" | tee -a /etc/log-create-vmess.log
echo -e "Port TLS : 443 ${tls}" | tee -a /etc/log-create-vmess.log
echo -e "Port none TLS : 80 ${none}" | tee -a /etc/log-create-vmess.log
echo -e "Port gRPC : ${tls}" | tee -a /etc/log-create-vmess.log
echo -e "id : ${uuid}" | tee -a /etc/log-create-vmess.log
echo -e "alterId : 0" | tee -a /etc/log-create-vmess.log
echo -e "Security : auto" | tee -a /etc/log-create-vmess.log
echo -e "Network : ws" | tee -a /etc/log-create-vmess.log
echo -e "Path : /vmess" | tee -a /etc/log-create-vmess.log
echo -e "ServiceName : vmess-grpc" | tee -a /etc/log-create-vmess.log
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m" | tee -a /etc/log-create-vmess.log
echo -e "Link TLS : ${vmesslink1}" | tee -a /etc/log-create-vmess.log
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m" | tee -a /etc/log-create-vmess.log
echo -e "Link none TLS : ${vmesslink2}" | tee -a /etc/log-create-vmess.log
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m" | tee -a /etc/log-create-vmess.log
echo -e "Link gRPC : ${vmesslink3}" | tee -a /etc/log-create-vmess.log
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m" | tee -a /etc/log-create-vmess.log
echo -e "Expired On : $exp" | tee -a /etc/log-create-vmess.log
echo -e "\033[0;34m━━━━

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m" | tee -a /etc/log-create-vmess.log
echo "" | tee -a /etc/log-create-vmess.log
read -n 1 -s -r -p "Press any key to back on menu"
done
