#!/bin/bash

# Backup Script for HOKAGE VPN STORE
# Created by: HOKAGE LEGEND
# Version: 1.0
# Description: This script backs up user data for migration to a new VPS

# Colors
red='\e[1;31m'
green='\e[0;32m'
yell='\e[1;33m'
tyblue='\e[1;36m'
NC='\e[0m'

# Check if running as root
if [ "${EUID}" -ne 0 ]; then
    echo -e "${red}You need to run this script as root${NC}"
    exit 1
fi

# Create backup directory
BACKUP_DIR="/root/hokage_backup_$(date +"%Y%m%d_%H%M%S")"
mkdir -p $BACKUP_DIR
mkdir -p $BACKUP_DIR/etc
mkdir -p $BACKUP_DIR/var/lib
mkdir -p $BACKUP_DIR/usr/local/etc

# Backup function
function backup_data() {
    echo -e "${green}Starting backup process...${NC}"
    
    # Backup user accounts
    echo -e "${yell}Backing up user accounts...${NC}"
    cp -r /etc/passwd $BACKUP_DIR/etc/
    cp -r /etc/shadow $BACKUP_DIR/etc/
    cp -r /etc/group $BACKUP_DIR/etc/
    cp -r /etc/gshadow $BACKUP_DIR/etc/
    
    # Backup SSH keys and configurations
    echo -e "${yell}Backing up SSH data...${NC}"
    cp -r /etc/ssh $BACKUP_DIR/etc/
    cp -r /root/.ssh $BACKUP_DIR/
    
    # Backup VPN configurations
    echo -e "${yell}Backing up VPN configurations...${NC}"
    cp -r /etc/openvpn $BACKUP_DIR/etc/
    
    # Backup Xray/V2Ray configurations

    echo -e "${yell}Backing up Xray/V2Ray configurations...${NC}"
    cp -r /etc/xray $BACKUP_DIR/etc/
    cp -r /etc/v2ray $BACKUP_DIR/etc/
    
    # Backup HOKAGE specific files
    echo -e "${yell}Backing up HOKAGE specific files...${NC}"
    cp -r /etc/hokagevpn $BACKUP_DIR/etc/
    cp -r /var/lib/hokagevpn-pro $BACKUP_DIR/var/lib/
    cp -r /var/lib/ipvps.conf $BACKUP_DIR/var/lib/
    cp -r /usr/local/etc/.$Name.ini $BACKUP_DIR/usr/local/etc/
    
    # Backup domain information
    echo -e "${yell}Backing up domain information...${NC}"
    cp -r /etc/xray/domain $BACKUP_DIR/etc/xray/
    cp -r /etc/v2ray/domain $BACKUP_DIR/etc/v2ray/
    cp -r /etc/xray/scdomain $BACKUP_DIR/etc/xray/
    cp -r /etc/v2ray/scdomain $BACKUP_DIR/etc/v2ray/
    
    # Backup log files
    echo -e "${yell}Backing up log files...${NC}"
    cp -r /etc/log-create-ssh.log $BACKUP_DIR/etc/
    cp -r /etc/log-create-vmess.log $BACKUP_DIR/etc/
    cp -r /etc/log-create-vless.log $BACKUP_DIR/etc/
    cp -r /etc/log-create-trojan.log $BACKUP_DIR/etc/
    cp -r /etc/log-create-shadowsocks.log $BACKUP_DIR/etc/
    
    # Backup cron jobs
    echo -e "${yell}Backing up cron jobs...${NC}"
    crontab -l > $BACKUP_DIR/crontab_backup
    
    # Create compressed archive
    echo -e "${yell}Creating compressed backup file...${NC}"
    tar -czvf /root/hokage_backup.tar.gz $BACKUP_DIR > /dev/null 2>&1
    
    # Cleanup
    rm -rf $BACKUP_DIR
    
    echo -e "${green}Backup completed successfully!${NC}"
    echo -e "${tyblue}Backup file created at: /root/hokage_backup.tar.gz${NC}"
}

# Restore function (for reference, to be used on new VPS)
function restore_instructions() {
    echo -e "\n${tyblue}===== RESTORE INSTRUCTIONS =====${NC}"
    echo -e "To restore this backup on a new VPS:"
    echo -e "1. Copy the backup file to the new VPS"
    echo -e "2. Extract it: ${green}tar -xzvf hokage_backup.tar.gz${NC}"
    echo -e "3. Run the restore script that will be included in the backup"
    echo -e "4. Or manually copy files to their respective locations"
    echo -e "Note: Make sure to install all required packages first${NC}"
}

# Main menu
clear
echo -e "${tyblue}==================================${NC}"
echo -e "${tyblue}    HOKAGE VPN BACKUP SCRIPT      ${NC}"
echo -e "${tyblue}==================================${NC}"
echo -e "${green}1. Backup all user data${NC}"
echo -e "${green}2. Show restore instructions${NC}"
echo -e "${red}3. Exit${NC}"
echo -e "${tyblue}==================================${NC}"

read -p "Select an option [1-3]: " option

case $option in
    1)
        backup_data
        ;;
    2)
        restore_instructions
        ;;
    3)
        echo -e "${red}Exiting...${NC}"
        exit 0
        ;;
    *)
        echo -e "${red}Invalid option!${NC}"
        exit 1
        ;;
esac
